### PR TITLE
added solution to 4.3 and 4.4 books rental

### PR DESCRIPTION
**Pull request by spyguyrajat**
Please add this to the main repository for complete solutions to 4.3 and 4.4 of Book rental sprint.

### CODE REVIEW

**Comment by anshumanbiswal14** [comment]
Thanks buddy !

**Comment by anshumanbiswal14** [comment]
Also Did you get Book Rental Sprint 2 Assignment 3/ outcome 3 RENT BOOKS? I
am getting 50/100

**Comment by spyguyrajat** [comment]
Rent Books


<html>
    <head>
        <title> Rent Books </title>
        <script>
            function ShowRent()
            {
                var name= document.getElementById("name").value;
                var days=parseInt(document.getElementById("tenure").value);
                rent_amt=100;
                var qty= parseInt(document.getElementById("total").value);
                rent = 100 * days * qty;
                val=confirm("Rent for Books Selected:" + rent);
                if (val==true)
                    alert("Thank You for Order" + name);
                 }

            function CheckName()
            {
                var name= document.getElementById("name").value;
                if(/[a-zA-Z]{5,}/.test(name))
                    alert("Name ok");
                else
                    alert("Minimum 5 Characters and only one special
character allowed");
            }

            function CheckRent()
            {
                var rent=document.getElementById("tenure").value;
                if(rent>30)
                    alert("We cannot rent over than 30 days");
                else
                    alert("Allowed");
            }
        </script>
    </head>
    <body>
        <h2><span style="background color:#000080; color:#ff6600;">Rent
Books</span></h2>
        <table>
            <tr><td>Book Name</td>
            <td><select>
                <option>HTML</option>
                <option>DBMS</option>
                <option>SE</option>
                <option>JAVA</option>
                <option>PYTHON</option>
                <option>ML</option>

            </select></td></tr>
            <tr><td>User Name</td><td><input type="text" id="name"
onblur="CheckName()"/></td></tr>
            <tr><td>Rent Start Date</td><td><input type="text"
id="startdate" placeholder="mm/dd/yyyy"/></td></tr>
            <tr><td>Rent Tenure</td><td><input type="text" id="tenure"
onblur="CheckRent()"/></td></tr>
            <tr><td>Number of Books Available</td><td><input type="text"
id="toysavail"/></td></tr>
            <tr><td>Enter number of Books</td><td><input type="text"
id="numoftoys"/></td></tr>
            <tr><td></td><td><input type="button" onclick="ShowRent()"
value="Submit Query" /></td></tr>
        </table>
    </body>
</html>

**Comment by ayugupta29** [comment]
Can add js file for user registration in sprint 2.

**Pull request closed without merging**
